### ISSUE TITLE
Properly configure TLS

### ISSUE THREAD

**Issue by ctron** [EnMasseProject/enmasse.io#3]
enmasse.io still is only available via HTTP and not via HTTPS … 

My understanding is that this is the case as `enmasse.io` is configured with `A` records, instead of  `ALIAS`:

~~~
;; ANSWER SECTION:
enmasse.io.		374	IN	A	192.30.252.154
enmasse.io.		374	IN	A	192.30.252.153
~~~

https://github.blog/2018-05-01-github-pages-custom-domains-https/

**Comment by lulf** [comment]
I've updated the A records now, give it somewhere between 10 minutes and 1 hour to update :)

**Comment by ctron** [comment]
I can see the updated A records, however I still see the old TLS certificate. Did you do the last step as well?

> If you're updating the IP address of an existing A record, first remove and then re-add your custom domain to the repository you’re using to publish your Pages site to trigger the process of enabling HTTPS.

**Comment by lulf** [comment]
Ah, forgot about that. Did that now

**Comment by k-wall** [comment]
Closing, looks like this is done.
